### ISSUE TITLE
Compiling heavy Unity Android plugin for 64-bit architecture

### ISSUE THREAD

**Issue by Shantibhushan95** [enzienaudio/hvcc#20]
Now that Google Play wants you to include plugins for 64-bit architectures, how do you compile the heavy plugin for Unity - Android arm64-v8a, x86 and x86_64?
I tried changing the APP_ABI and APP_PLATFORM flags, but it didn't work.

**Comment by moiseshorta** [comment]
Hi @Shantibhushan95 , did you ever find a solution for this?

thanks!

**Comment by Shantibhushan95** [comment]
@moiseshorta 

Nope! And now this has become an urgent issue for me.

**Comment by Shantibhushan95** [comment]
@moiseshorta 

Hi! The compiler successfully compiles for ARM 32-bit and 64-bit devices (armeabi-v7a and arm64-v8a) by changing the APP_ABI in Application.mk appropriately, but not for Intel x86 and x86_64.

I read this: https://android.stackexchange.com/questions/186334/what-percentage-of-android-devices-runs-on-x86-architecture and left the worry for other architectures.

**Comment by Shantibhushan95** [comment]
@moiseshorta 

It's late, but there's a fix!

You need to comment out the following lines in Android.mk

`LOCAL_CFLAGS := -std=c11 -DNDEBUG -DHV_SIMD_NEON -O3 -ffast-math -fPIC`
`LOCAL_ARM_NEON := true`
`LOCAL_ARM_MODE := arm`

And add this check for each module within Application.mk

`ifeq ($(TARGET_ARCH),arm)`
`LOCAL_ARM_NEON := true`
`LOCAL_ARM_MODE := arm`
`LOCAL_CFLAGS := -std=c11 -DNDEBUG -DHV_SIMD_NEON -O3 -ffast-math -fPIC`
`endif`
`ifeq ($(TARGET_ARCH),x86_64)`
`LOCAL_CFLAGS := -std=c11 -DNDEBUG -DHV_SIMD_NONE -O3 -ffast-math -fPIC`
`endif`

And set the following flag in Application.mk, for now it compiles for every arch

`APP_ABI := all`
