### ISSUE TITLE
Not outputting .dll files

### ISSUE THREAD

**Issue by quicklyplz** [enzienaudio/hvcc#5]
Trying to generate a Wwise plugin and HVCC is only outputting the .xml file, but nothing else. I've tried simplifying the Pd patch just to test and it's still not working. Am I missing something stupid?

compiled using this line:
python hvcc.py ../pd/TEST.pd -o ../output/ -n TEST -g wwise

**Comment by quicklyplz** [comment]
Never mind I figured it out

**Comment by giuliomoro** [comment]
The generator build the project to be compiled, but does not do the compilation step itself.
